# Generated by Django 6.0.5 on 2026-06-12 07:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleview',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='articleview',
            name='articles_ar_article_f8b9ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='articleview',
            name='articles_ar_viewed__e444cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='articles_co_article_1d93b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='reaction',
            name='articles_re_article_fbd103_idx',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
