# Generated by Django 5.2.14 on 2026-06-07 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_comment_parent_comment_updated_at_alter_comment_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reaction",
            name="unique_user_reaction",
        ),
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together={("article", "user")},
        ),
        migrations.AddField(
            model_name="reaction",
            name="reacted_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="reaction",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("love", "Love"),
                    ("wow", "Wow"),
                    ("SAD", "Sad"),
                ],
                default="like",
                max_length=10,
            ),
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="created_at",
        ),
    ]
