# Generated by Django 5.2.14 on 2026-06-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_remove_reaction_unique_user_reaction_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={},
        ),
    ]
