# Generated by Django 5.2.14 on 2026-06-07 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_tag_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterField(
            model_name="reaction",
            name="reaction",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("love", "Love"),
                    ("wow", "Wow"),
                    ("sad", "Sad"),
                ],
                default="like",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["article", "created_at"], name="articles_co_article_1d93b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(
                fields=["article", "reaction"], name="articles_re_article_fbd103_idx"
            ),
        ),
    ]
