# Generated by Django 6.0.5 on 2026-06-12 07:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('client_name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='ad_banners/')),
                ('target_url', models.URLField()),
                ('position', models.CharField(choices=[('top_banner', 'Top Banner (728x90)'), ('sidebar', 'Sidebar Box (300x250)'), ('in_article', 'In-Article Strip (468x60)'), ('footer', 'Footer Banner (728x90)'), ('popup', 'Overlay Popup')], db_index=True, max_length=20)),
                ('is_sponsored_article', models.BooleanField(db_index=True, default=False)),
                ('sponsored_article_id', models.PositiveIntegerField(blank=True, help_text='If this is a sponsored article, provide its Article ID', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(help_text='Campaign expiration date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Choose a specific category to target (e.g., Sports). Leave blank for site-wide ads.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_ads', to='articles.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_impressions', to=settings.AUTH_USER_MODEL)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='ads.advertisement')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_clicks', to=settings.AUTH_USER_MODEL)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='ads.advertisement')),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
    ]
