# Generated by Django 5.2.14 on 2026-06-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_role"),
        ("user", "0004_alter_passwordresettoken_id_alter_refreshtoken_id_and_more"),
    ]

    operations = []
